version: "3.9"

services:
  app:
    build: .
    container_name: ia_flask_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/fabiodb
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo_fabio
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
